### ISSUE TITLE
empty organization created on user registration

### ISSUE THREAD

**Issue by J-Morocho** [Tech-NYC/Sharity#74]

**Comment by pitoms** [comment]
Problem does not persist on hand built http requests. Switching over to client side to see if the error is in request creation.

**Comment by pitoms** [comment]
Confirmed single call of submit function and proper request created

![image (2)](https://user-images.githubusercontent.com/9123958/115098942-dbb7bc00-9f00-11eb-94d9-3c9271cfa2ac.png)

**Comment by pitoms** [comment]
Because of cross-origin policies on local dev - I'll be adding log messages to our serverside endpoints temporarily. Now attempting to trace the complete lifecycle of a request response.

**Comment by pitoms** [comment]
Problem seems to resolve when removing certain awaits within register on index,js serverside. However removal of awaits removes guarantee of our queries to be run sequentially.
